services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vet_system
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    restart: unless-stopped

  app:
    build: .
    container_name: vet_app
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    environment:
      DB_HOST: mysql
      DB_NAME: vet_system
      DB_USER: root
      DB_PASSWORD: root
    depends_on:
      - mysql
    restart: unless-stopped

volumes:
  mysql_data:
